[tool.black]
line-length = 160
[tool.poetry]
name = "siem-query-utils"
version = "1.3.6"
description = ""
authors = ["Adon Metcalfe <adonm@fastmail.fm>"]
readme = "README.md"
packages = [{include = "siem_query_utils"}]

[tool.poetry.dependencies]
python = "^3.10"
azure-cli = "^2.41.0"
fastapi = {extras = ["all"], version = "^0.85.1"}
fire = "^0.4.0"
cacheout = "^0.14.1"
markdown = "^3.4.1"
flatten-json = "^0.1.13"
pathvalidate = "^2.5.2"
python-dotenv = "^0.21.0"
httpx-cache = "^0.6.1"
cloudpathlib = "^0.10.0"
azure-storage-blob = "^12.14.1"
pandas = "^1.5.1"

[tool.poetry.scripts]
siem_query_utils = "siem_query_utils:cli"

[tool.poetry.group.dev.dependencies]
black = {version = "^22.10.0", allow-prereleases = true}

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
